service:
  name: serverless-image-resizer

plugins:
  - serverless-webpack
  - serverless-s3-local
  - serverless-apigw-binary
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  region: ${env:region, 'ap-south-1'}
  stage: ${env:stage, 'dev'}
  endpointType: REGIONAL
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:ListBucket
      Resource:
        - 'arn:aws:s3:::${self:custom.bucketName}'
    - Effect: Allow
      Action:
        - s3:getObject
      Resource:
        - 'arn:aws:s3:::${self:custom.bucketName}/*'

custom:
  bucketName: rb-assets-${self:provider.stage}
  s3:
    host: 0.0.0.0
    port: 5445
    directory: .
    cors: false
  webpack:
    includeModules:
      forceInclude:
        - sharp
    packager: 'npm'
  apigwBinary:
    types:
      - '*/*'

functions:
  processor:
    handler: src/index.handle
    timeout: 15
    memorySize: 3008
    environment:
      BUCKET: ${self:custom.bucketName}
    events:
      - http:
          method: get
          path: /{proxy+}
          cors: true

resources:
  Resources:
    WebDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Origins:
            - Id: ImageOrigin
              DomainName:
                Fn::Join:
                  - ""
                  - - Ref: ApiGatewayRestApi
                    - ".execute-api."
                    - ${self:provider.region}
                    - ".amazonaws.com"
              OriginPath: "/${self:provider.stage}"
              CustomOriginConfig:
                OriginProtocolPolicy: https-only
          Enabled: true
          HttpVersion: http2
          DefaultCacheBehavior:
            AllowedMethods:
              - GET
              - HEAD
            TargetOriginId: ImageOrigin
            ForwardedValues:
              QueryString: true
              Headers:
                - Accept
            ViewerProtocolPolicy: allow-all
  Outputs:
    WebDistributionUrl:
      Description: "Cloudfront url"
      Value:
        Fn::GetAtt: WebDistribution.DomainName